name        = "jo-library"
namespace   = "jo"
description = "Core standard library for the Jo language"
url         = "https://jo-lang.org"
repo        = "https://github.com/typescope/jo"
registered  = "2026-03-26"
runtime     = "pure"

[owner]
name  = "TypeScope"
email = "fengyun.liu@typescope.ai"

[publish]
github = "typescope/jo"
